### PR TITLE
added example testing

### PR DESCRIPTION
**Pull request by mcritz**
I drafted this example of using XCTest with hummingbird app

### CODE REVIEW

**Comment by adam-fowler** [comment]
Hi, you're right a testing example would be useful. 

I'm planning to write a template project for a hummingbird project. It'd be great once that is up if you could follow that template. I'll be changing all the other examples to follow it once it is up. It won't be far off what you've built here. A `server` executable and an `app` library. As you can't run tests off the executable they need to be run off the library.

One thing your example will need to make clear and provide for is the different test frameworks. `embedded` using the `EmbeddedChannel` doesn't run a server it just tests the routes and because it is using an `EmbeddedChannel` cannot interact with other threads or services. The `live` setup starts up a local server to do testing and can test everything. In most cases I imagine people would be using `live` because they will be interacting for other services eg databases, redis.

**Comment by mcritz** [comment]
@adam-fowler sounds great. Please ping me when that template is ready. I'll make the other changes now. M

**Comment by adam-fowler** [comment]
@mcritz https://github.com/hummingbird-project/template

**Comment by mcritz** [comment]
Great! I can rewrite as much as needed to match the template.

**Comment by mcritz** [comment]
@adam-fowler Looks like the template is accomplishing everything I set out to in this PR. Going to close.

**Comment by adam-fowler** [comment]
@mcritz I think it is still worthwhile adding an example with a more complex setup. Maybe trying to get across the difference between using `HBApplication(testing: .embedded)` and `HBApplication(testing: .live)`

**Pull request closed without merging**
