### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xavgru12**

### CODE REVIEW

**Comment by xavgru12** [comment]
For some reason my editor used the wrong „-„. The link works now.

**Review by adam-fowler — COMMENTED** [review]
What's the difference. Is it a slightly different character?

**Review by adam-fowler — APPROVED** [review]
This time I verified the link works

**Comment by adam-fowler** [comment]
Thanks again

**Comment by xavgru12** [comment]
I looked the difference up: The usual dash is the en dash. My editor used the em dash. It is just slightly longer.

**Pull request merged**
